name: abmap
dependencies:
- bioconda::hmmer>=3.0 # NOTE - using biocore as the channel caused dependency issues
- bioconda::anarci
- schrodinger::pymol # NOTE - PyMOL 2.5 is on conda-forge: https://pymol.org/conda/
- conda-forge::tape_proteins
- ipykernel
- pip # TODO - specify which pip
- pip:
  - Bio>=1.5.3
  - dscript~=0.2.2
  - embed>=0.1.0
  - h5py~=3.8.0
  - matplotlib>=3.7.0
  - numpy>=1.23.4
  - pandas>=1.5.1
  - positional_encodings~=6.0.1
  # - pymol>=0.1.0 --> moved to conda install (see above)
  - PyQt5 # for macOS users using 
  - scikit_learn>=1.2.1
  - scipy>=1.10.0
  - seaborn>=0.12.2
  # - tape~=1.0 --> moved to conda install (see above)
  - torch~=1.13.1
  - tqdm>=4.64.1
  - transformers~=4.26.1
  - twine>=1.13.0
